version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    restart: always
  app:
    image: gradle:jdk8-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: gradle bootRun
    restart: always